---
AWSTemplateFormatVersion: 2010-09-09


#-------------------------------------------------------------------------------
Description: >
  AWS S3 backup : master template

#-------------------------------------------------------------------------------
Metadata:
  #
  Authors:
    Description: F. Barmes
  #
  #
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "General Parameters"
        Parameters:
          - EnvironmentName
      -
        Label:
          default: "S3 Parameters"
        Parameters:
          - BucketName
          - T1TimeInDays
          - T1StorageClass
          - T2TimeInDays
          - T2StorageClass
          - EnableVersioning
          - NoncurrentVersionExpirationInDays
          - ExpirationInDays
          - EnableLogging
          - LogExpirationTimeInDays
      -
        Label:
          default: "IAM Parameters"
        Parameters:
          - IAMPath
    ParameterLabels:
      EnvironmentName:
        default: "Name of this environement"
      BucketName:
        default: "Name of the data bucket"
      IAMPath:
        default: "IAM path for the created IAM resources"

#-------------------------------------------------------------------------------
Parameters:
  #-------------------------------------
  # CFN parameters
  #-------------------------------------
  #
  CfnBucket:
    Description: The template bucket for the CloudFormation templates
    Type: String
    Default: "fbarmes-cfn-public"
  #
  CfnPath:
    Type: String
    Description: a path in the S3 bucket to find the CloudFormation templates root
    Default: "aws-s3-backup"
  #
  #-------------------------------------
  # General parameters
  #-------------------------------------
  EnvironmentName:
    Description: Environment name (dev, prod)
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  #
  #-------------------------------------
  # S3 parameters
  #-------------------------------------
  BucketName:
    Description: Name of the S3 bucket that is created
    Type: String
    AllowedPattern: ".+"

  T1TimeInDays:
    Description: 'time fater which an object undergoes Transition T1 (IT, IA or OneZoneIA)'
    Type: Number
    MinValue: 30
    Default: 30

  T1StorageClass:
    Description: 'target storage class for transition T1'
    Type: String
    Default: STANDARD_IA
    AllowedValues:
      - INTELLIGENT_TIERING
      - STANDARD_IA
      - ONEZONE_IA

  T2TimeInDays:
    Description: 'time fater which an object undergoes Transition T2 (to GLACIER)'
    Type: Number
    MinValue: 30
    Default: 90

  T2StorageClass:
    Description: 'target storage class for transition T2'
    Type: String
    Default: GLACIER
    AllowedValues:
      - GLACIER

  EnableVersioning:
    Description: 'Enable versioning to keep a backup if objects change.'
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false', 'false-but-was-true']

  NoncurrentVersionExpirationInDays:
    Description: 'Delete old version of objects after X days (set 0 to disable)'
    Type: Number
    Default: 7
    MinValue: 0

  ExpirationInDays:
    Description: 'Delete object after X days (set 0 to disable)'
    Type: Number
    Default: 0
    MinValue: 0

  EnableLogging:
    Description: Enable a bucket that stores the logs
    Type: String
    AllowedValues:
      - true
      - false
    Default: false

  LogExpirationTimeInDays:
    Description: duration in day after which log objects are deleted
    Type: Number
    MinValue: 1
    Default: 15

  #
  #-------------------------------------
  # IAM parameters
  #-------------------------------------
  IAMPath:
    Description: IAM Path for the resources created by this stack
    Type: String
    Default: '/s3-backup/'


#-------------------------------------------------------------------------------
Resources:
  #
  #-----------------------------------------------------------------------------
  # S3Stack
  #-----------------------------------------------------------------------------
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${CfnBucket}/${CfnPath}/templates/010-s3.yml
      Parameters:
        BucketName: !Ref 'BucketName'
        T1TimeInDays: !Ref 'T1TimeInDays'
        T1StorageClass: !Ref 'T1StorageClass'
        T2TimeInDays: !Ref 'T2TimeInDays'
        T2StorageClass: !Ref 'T2StorageClass'
        EnableVersioning: !Ref 'EnableVersioning'
        NoncurrentVersionExpirationInDays: !Ref 'NoncurrentVersionExpirationInDays'
        ExpirationInDays: !Ref 'ExpirationInDays'
        EnableLogging: !Ref 'EnableLogging'
        LogExpirationTimeInDays: !Ref 'LogExpirationTimeInDays'
  #
  #-----------------------------------------------------------------------------
  # IAMStack
  #-----------------------------------------------------------------------------
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${CfnBucket}/${CfnPath}/templates/011-iam.yml
      Parameters:
        BucketArn: !GetAtt S3Stack.Outputs.DataBucketArn
        IAMPath: !Ref 'IAMPath'

#-------------------------------------------------------------------------------
Outputs:
  #
  DataBucketName:
    Description: Name of the bucket created
    Value: !GetAtt S3Stack.Outputs.DataBucketName
  #
  UserName:
    Description: Name of the user for this stack
    Value: !GetAtt IAMStack.Outputs.UserName
  #
  AccessKey:
    Description: Access key for accessing the S3 Bucket
    Value: !GetAtt IAMStack.Outputs.AccessKey
  #
  SecretKey:
    Description: Secret key for accessing the S3 Bucket
    Value: !GetAtt IAMStack.Outputs.SecretKey
